### PR TITLE
Uploading  Return Refund Policy

### PR DESCRIPTION
**Pull request by Rajeev9813**

### CODE REVIEW

**Review by Rajeev9813 — COMMENTED** [review]
Aprroval needed ?

**Review by Rajeev9813 — COMMENTED** [review]
approval needed for another page

**Review by Rajeev9813 — COMMENTED** [review]
approval needed ?

**Review by BibekKumarKushwaha — APPROVED** [review]

**Review by BibekKumarKushwaha — APPROVED** [review]

**Review by raziruu — APPROVED** [review]
Approved

**Review by sarukhadka1 — APPROVED** [review]
approved

**Pull request merged**
