### PR TITLE
Added Updated ItemCart

### PR DESCRIPTION
**Pull request by Rajeev9813**

### CODE REVIEW

**Review by Rajeev9813 — COMMENTED** [review]
approve ?

**Review by sarukhadka1 — APPROVED** [review]

**Review by sarukhadka1 — APPROVED** [review]

**Review by BibekKumarKushwaha — APPROVED** [review]

**Comment by krishalsatta** [comment]
approved

**Review by sarukhadka1 — APPROVED** [review]

**Review by BibekKumarKushwaha — APPROVED** [review]

**Comment by krishalsatta** [comment]
approved

**Review by krishalsatta — COMMENTED** [review]
approved

**Review by krishalsatta — APPROVED** [review]
approved

**Pull request merged**
