### PR TITLE
Adding Custom Buttons and Icons 

### PR DESCRIPTION
**Pull request by Rajeev9813**

### CODE REVIEW

**Review by Rajeev9813 — COMMENTED** [review]
approval ?

**Review by Rajeev9813 — COMMENTED** [review]
approval

**Review by BibekKumarKushwaha — APPROVED** [review]

**Review by sarukhadka1 — APPROVED** [review]
approved

**Review by krishalsatta — APPROVED** [review]
approved

**Review by raziruu — APPROVED** [review]
approved

**Pull request merged**
