### PR TITLE
Added Product Detail.dart

### PR DESCRIPTION
**Pull request by Rajeev9813**

### CODE REVIEW

**Review by Rajeev9813 — COMMENTED** [review]
review

**Review by krishalsatta — APPROVED** [review]
approved

**Review by Rajeev9813 — COMMENTED** [review]
approve ?

**Comment by krishalsatta** [comment]
> approve ?

**Comment by krishalsatta** [comment]
approved

**Review by Rajeev9813 — COMMENTED** [review]
approve ?

**Review by Rajeev9813 — COMMENTED** [review]
approve?

**Review by Rajeev9813 — COMMENTED** [review]
approve ?

**Comment by krishalsatta** [comment]
approved

**Review by Rajeev9813 — COMMENTED** [review]
approve ?

**Review by Rajeev9813 — COMMENTED** [review]
approve ?

**Review by sarukhadka1 — APPROVED** [review]

**Review by BibekKumarKushwaha — APPROVED** [review]

**Pull request merged**
