### PR TITLE
Krishal

### PR DESCRIPTION
**Pull request by krishalsatta**
approve ?

### CODE REVIEW

**Review by Rajeev9813 — APPROVED** [review]
approved

**Review by Rajeev9813 — APPROVED** [review]
approved three of them

**Review by krishalsatta — COMMENTED** [review]
approve please

**Review by sarukhadka1 — APPROVED** [review]

**Review by Rajeev9813 — APPROVED** [review]
approved OTP verification

**Review by sarukhadka1 — APPROVED** [review]

**Review by krishalsatta — COMMENTED** [review]
approve please

**Review by sarukhadka1 — APPROVED** [review]

**Review by BibekKumarKushwaha — APPROVED** [review]

**Pull request merged**
