### PR TITLE
add to cart

### PR DESCRIPTION
**Pull request by krishalsatta**
approve ????

### CODE REVIEW

**Review by Rajeev9813 — APPROVED** [review]
Approved

**Review by BibekKumarKushwaha — APPROVED** [review]
approve

**Review by raziruu — APPROVED** [review]
approved

**Review by raziruu — APPROVED** [review]
approved

**Review by sarukhadka1 — APPROVED** [review]

**Review by krishalsatta — COMMENTED** [review]
approve?

**Review by krishalsatta — COMMENTED** [review]
approve please

**Pull request merged**
